- hosts: localhost
  connection: local
  tasks:
    - name: Clone or update upstream project-config
      git:
        repo: https://opendev.org/openstack-infra/project-config
        dest: /usr/share/project-config
        force: yes
