- hosts: zm02.softwarefactory-project.io
  gather_facts: no
  user: centos
  vars:
    desired_hostname: zm02.softwarefactory-project.io
  tasks:
    - name: Authorize root ssh access
      command: sed -e 's/no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command=.echo .Please login as the user .*echo;sleep 10. //' -i /root/.ssh/authorized_keys 
      become: yes

    - name: Fix hostname
      copy:
        content: "{{ desired_hostname }}"
        dest: /etc/hostname
      become: yes

    - name: Update hostname now
      command: hostname -F /etc/hostname
      become: yes

    - name: Fix centos var
      copy:
        content: "centos"
        dest: /etc/yum/vars/contentdir
      become: yes

    - name: Add repo packages
      yum:
        name: '{{ item }}'
        state: present
        disablerepo: '{{ yum_disable_repo|default(omit) }}'
        enablerepo: '{{ yum_enable_repo|default(omit) }}'
      with_items:
        - centos-release-openstack-queens
        - centos-release-scl-rh
      become: yes

    - name: Set 3.1 (master) repo
      copy:
        content: |
          [sfrelease-master]
          name=SF master packages
          baseurl=http://38.145.34.53/kojifiles/repos/sf-master-el7/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-SOFTWARE-FACTORY
          gpgcheck=0
          enabled=1
        dest: /etc/yum.repos.d/sf-release.repo
      become: yes

    - name: Force current version
      copy:
        content: "3.1"
        dest: /etc/sf-release
      become: yes

    - name: Ensure /var/lib/sf exists
      file:
        path:  /var/lib/software-factory/
        state: directory
      become: yes

    - name: Force previous version
      copy:
        content: "3.0"
        dest: /var/lib/software-factory/.version
      become: yes

    - name: Update system
      yum:
        name: '*'
        state: latest
      become: yes

- hosts: install-server
  roles:
  - sf-ssh
  vars:
    role_action: populate_hosts

- any_errors_fatal: true
  hosts: all:!hypervisor-runc
  tasks:
    - name: Copy /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
