- hosts: ze05.softwarefactory-project.io
  gather_facts: no
  user: centos
  vars:
    desired_hostname: ze05.softwarefactory-project.io
  tasks:
    - name: Authorize root ssh access
      command: sed -e 's/no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command=.echo .Please login as the user .*echo;sleep 10. //' -i /root/.ssh/authorized_keys
      become: yes

    - name: Fix hostname
      copy:
        content: "{{ desired_hostname }}"
        dest: /etc/hostname
      become: yes

    - name: Update hostname now
      command: hostname -F /etc/hostname
      become: yes

    - name: Fix centos var
      copy:
        content: "centos"
        dest: /etc/yum/vars/contentdir
      become: yes

    - name: Add repo packages
      yum:
        name: '{{ item }}'
        state: present
        disablerepo: '{{ yum_disable_repo|default(omit) }}'
        enablerepo: '{{ yum_enable_repo|default(omit) }}'
      with_items:
        - centos-release-openstack-queens
        - centos-release-scl-rh
      become: yes

    - name: Install release repository
      yum:
        name: https://softwarefactory-project.io/repos/sf-release-3.1.rpm
      become: yes

    - name: Update system
      yum:
        name: '*'
        state: latest
      become: yes

- hosts: install-server
  roles:
  - sf-ssh
  vars:
    role_action: populate_hosts

- any_errors_fatal: true
  hosts: all:!hypervisor-runc
  tasks:
    - name: Copy /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
