---
- hosts: zuul-executor:zuul-merger:zuul-scheduler
  tasks: []
    # Optional, install a new version
    #- yum:
    #    name: https://softwarefactory-project.io/logs/27/12827/2/check/sf-rpm-build/a2a9ed1/buildset/rh-python35-zuul-3.1.0-4.20180629git0268285.el7.noarch.rpm
    #    state: present

- hosts: zuul-executor
  tasks:
    - command: /opt/rh/rh-python35/root/bin/zuul-executor stop

- hosts: zuul-scheduler
  tasks:
    - command: zuul-changes.py dump --dump_file /root/zc.sh
    - service:
        name: rh-python35-zuul-scheduler
        state: stopped

- hosts: zuul-merger
  tasks:
    - service:
        name: rh-python35-zuul-merger
        state: restarted

- hosts: zuul-executor
  tasks:
    - service:
        name: rh-python35-zuul-executor
        state: restarted

- hosts: zuul-scheduler
  tasks:
    - service:
        name: rh-python35-zuul-scheduler
        state: restarted

- hosts: zuul-web
  tasks:
    - service:
        name: rh-python35-zuul-web
        state: restarted
    - uri:
        url: "{{ zuul_web_url }}/api/tenant/{{ tenant_name }}/pipelines"
        return_content: yes
        status_code: "200"
      register: _zuul_status
      until: "'json' in _zuul_status and _zuul_status.json and 'periodic' in _zuul_status.content"
      retries: 900
      delay: 2

- hosts: zuul-scheduler
  tasks:
    - command: bash /var/lib/software-factory/state/zuul-change-dump.sh
