- hosts: localhost
  connection: local
  tasks:
    - name: "Create local backup directory {{ local_dir }}"
      file:
        path: "{{ local_dir }}"
        state: directory
        mode: 0700
    - name: "Create local bup directory {{ bup_dir }}"
      file:
        path: "{{ bup_dir }}"
        state: directory
        mode: 0700
    - stat:
        path: "{{ bup_dir }}/HEAD"
      register: bd
    - name: "Bup init"
      command: "bup init"
      environment:
        BUP_DIR: "{{ bup_dir }}"
      when: not bd.stat.exists
- hosts: sf
  tasks:
    - name: "Run sf_backup playbook on the remote SF"
      command: "ansible-playbook /var/lib/software-factory/ansible/sf_backup.yml"
      when: run_sf_backup
    - name: "Rsync {{ remote_dir }} from remote SF to localhost {{ local_dir }}"
      synchronize:
        src: "{{ remote_dir }}"
        dest: "{{ local_dir }}"
        delete: yes
        recursive: true
        mode: pull
- hosts: localhost
  connection: local
  tasks:
    - name: "Bup index"
      command: "bup index {{ local_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
    - name: "Bup save"
      command: "bup save -n {{ bup_save_name }} {{ local_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
