- hosts: localhost
  connection: local
  tasks:
    - name: "Add {{ sf_host }} to the inventory"
      add_host:
        name: "{{ sf_host }}"
        groups: "sf"
    - name: "Set current_bup_dir"
      set_fact:
        current_bup_dir: "{{ bup_dir }}/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}"
    - name: "Create local backup directory {{ local_dir }}"
      file:
        path: "{{ local_dir }}"
        state: directory
        mode: 0700
    - name: "Create local bup directory {{ current_bup_dir }}"
      file:
        path: "{{ current_bup_dir }}"
        state: directory
        mode: 0700
    - stat:
        path: "{{ current_bup_dir }}/HEAD"
      register: bd
    - name: "Bup init"
      command: "bup init"
      environment:
        BUP_DIR: "{{ current_bup_dir }}"
      when: not bd.stat.exists

- hosts: sf
  tasks:
    - name: "Run sf_backup playbook on the remote SF"
      command: "ansible-playbook /var/lib/software-factory/ansible/sf_backup.yml"
      when: run_sf_backup

- hosts: localhost
  connection: local
  tasks:
    - name: "Rsync remote SF to localhost {{ local_dir }}"
      command: "rsync --delete-delay -r {{ sf_host }}:{{ remote_dir }} {{ local_dir }}"
    - name: "Bup index"
      command: "bup index {{ local_dir }}"
      environment:
        BUP_DIR: "{{ current_bup_dir }}"
    - name: "Bup save"
      command: "bup save -n {{ sf_host }} {{ local_dir }}"
      environment:
        BUP_DIR: "{{ current_bup_dir }}"
