- hosts: localhost
  connection: local
  tasks:
    - name: "Create local backup directory {{ local_backup_dir }}"
      file:
        path: "{{ local_backup_dir }}"
        state: directory
        mode: 0755
    - stat:
        path: "{{ bup_dir }}/HEAD"
      register: bd
    - name: "Bup init"
      command: "bup init"
      environment:
        BUP_DIR: "{{ bup_dir }}"
      when: not bd.stat.exists
    - name: "Rsync from remote server {{ remote_backuped_host }}:{{ remote_backuped_dir }}"
      command: "rsync -a --delete {{ remote_user}}@{{ remote_backuped_host }}:{{ remote_backuped_dir }} {{ local_backup_dir }}"
    - name: "Bup index"
      command: "bup index {{ local_backup_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
    - name: "Bup save"
      command: "bup save -n sf-backup {{ local_backup_dir }}"
      environment:
        BUP_DIR: "{{ bup_dir }}"
