- hosts: nodepool-launcher
  gather_facts: no
  vars:
    user_homes:
      - /root
      - /var/lib/nodepool
  tasks:
    - name: Ensure aws config directory exists, copy does not create
      file:
        path: "{{ item }}/.aws"
        mode: 0700
        state: directory
      with_items: "{{ user_homes }}"

    - name: Copy aws config
      copy:
        src: /etc/software-factory/aws.config
        dest: "{{ item }}/.aws/config"
        owner: nodepool
        group: nodepool
        mode: 0400
      with_items: "{{ user_homes }}"
